### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by zark-stark12** [jzarco/crm-rfm-modeling#1]
Feedback by anyone using this is welcome. This was written to automate a typical RFM modeling process I would work on where there was no available package I was able to find for Python. If anyone has any feedback in regards to it or any issues feel free to reach out.

**Comment by soliverc** [comment]
Hi, thanks for creating a package like this. I'm looking forward to using it. 

I just tried your example.py. Running it in jupyter. 

I can't import this package:

```python
import RFM_Model as rfm
```
```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-03e5aa4d8f56> in <module>
      1 import pandas as pd
----> 2 import RFM_Model as rfm
      3 from datetime import datetime
      4 from copy import deepcopy

ModuleNotFoundError: No module named 'RFM_Model'
```

I then decided to just import the packages in your main github readme:

```python
import crm_rfm_modeling
from crm_rfm_modeling import rfm
```

That works fine

Then I got another error here:

```python
#Default scoring method is "Quintile"
rfm.fit(data=data,dataset_type='transactional')

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-15-1e04ea7337cf> in <module>
      1 rfm = rfm.RFM(weights=wgts)
      2 #Default scoring method is "Quintile"
----> 3 rfm.fit(data=data,dataset_type='transactional')

~\Anaconda3\lib\site-packages\crm_rfm_modeling\rfm.py in fit(self, data, dataset_type, scoring_method, **kwargs)
     79             self.__dict__.update(catch_exception((k, v)) for k, v in kwargs.items())
     80 
---> 81             self.data = deepcopy(data)
     82             if boo_0:
     83                 if data.shape[1] != 3:

NameError: name 'deepcopy' is not defined
```

So it looks like I had to import deepcopy. 

```python
from copy import deepcopy
```

But this didn't work. I get the same error as above. It doesn't detect deepcopy even though I imported it myself. 

Any advice?

**Comment by soliverc** [comment]
OK - I figured out the RFM_Model problem.

You have an extra file called RFM_Model.py that I had to download an put in the same folder as my jupyer notebook. Seems to work now, no errors about deepcopy either.

**Comment by soliverc** [comment]
Would you be able to explain a bit how weights work? Before finding this library, I've been doing a few RFM Python tutorials and they don't mention weights. If they are useful I'd like to use them of course, but I'm not really sure how to use them.

**Comment by soliverc** [comment]
Also - the different scoring methods. 

Does 'mean' get the mean frequency and monetary per month? Same with 'median'? Is it per month?

**Comment by zark-stark12** [comment]
Hi. Thanks for bringing the errors to my attention. Will address those errors in a package update version as well as here on the repos.

@soliverc

To answer your question about the weights, in practice, some people depending on the client, industry, business etc. will hold certain variables (R-F-M) to have higher worth or weight with regards to other variables. The weighting system applies those weights (which sum to 1) to highlight which variables are more important comparatively against the others.

As for the scoring methods, they are taken from this paper: https://link.springer.com/article/10.1057/palgrave.jdm.3240019

Essentially for the scoring methods such as 'mean', what will happen is that it will recursively divide the segments based on the remaining customers as it build each scoring boundary one at a time as it does for the 'median' as well. If you want more information I would suggest reading the paper with regards to the scoring methods.

**Comment by soliverc** [comment]
Thanks for the info, will check the paper.

**Comment by zark-stark12** [comment]
please update and install to the latest version - pip install -U crm-rfm-modeling

Added additional options to include end date for transactional datasets along with another function to retrieve the fitted data.

Thanks again for the feedback.

**Comment by zark-stark12** [comment]
Additionally you can pip install such as: pip install crm-rfm-modeling==1.0.1
