### ISSUE TITLE
How to disable weights?

### ISSUE THREAD

**Issue by soliverc** [jzarco/crm-rfm-modeling#4]
I can see that weights are pre-set and must sum to 1

```python
    def __init__(self,weights=(0.2,0.2,0.6)):
        if sum(weights) == 1 and len(weights) == 3:
            self.weights = weights
        else:
            raise ValueError
```
What if I don't want to weight the scores?

**Comment by zark-stark12** [comment]
Hi @soliverc ,

If you don't want to use the weighted scores, the raw scores are available to you.

In the version 1.0.4, you are able to call the function ".get_fitted_data" to return the results of running the model. The results will show the unweighted scores along side the weighted scores. You can leave the scores as default. 

In future versions I will potentially consider adding an argument to weight the scores or not.
