### ISSUE TITLE
Updating to 1.0.3 broken?

### ISSUE THREAD

**Issue by soliverc** [jzarco/crm-rfm-modeling#6]
I was using version `1.0.1` for quite a while, then noticed today that there was a `1.0.3` version.

I updated via pip, and now the import doesn't work. 

![image](https://user-images.githubusercontent.com/47222261/73359713-60d19980-4299-11ea-996c-46cf686d4208.png)

The `.py` files for this package are also nowhere to be found on my computer. The only reference to your package is in `anaconda3\lib\site-packages\crm_rfm_modeling-1.0.3.dist-info\`. Can't find any actual .py files like I could with version 1.0.1.

I then uninstalled the package entirely and simply pip installed version 1.0.3 rather than updating. This didn't work either. 

I reverted back to `1.0.1` and everything works fine, `.py` files are present on my system.

**Comment by zark-stark12** [comment]
Hi @soliverc 

Thanks for bringing this to my attention. This appears to be an issue with how I uploaded the recent package to pypi. 

I've re-uploaded it to version 1.0.4

I've installed this version locally and the imports are working fine now. 

Let me know if you are still having this issue.

**Comment by soliverc** [comment]
Thanks for the quick reply.

**Comment by zark-stark12** [comment]
Since I haven't heard a reply regarding this I assume the issue has been resolved.
